name: Generate GitHub Contributions Snake

on:
  schedule:
    # every day at midnight UTC (adjust as you like)
    - cron: "0 0 * * *"
  workflow_dispatch: # allows manual run

jobs:
  build-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit & Push Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-artifacts
          path: dist/
